name: worktick
description: "WorkTick — ewidencja czasu pracy (Flutter + Firebase)"
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  # State, i18n, prefs
  provider: ^6.1.2
  easy_localization: ^3.0.7
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.3
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
# Material 3 jest wbudowany w Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/translations/
