// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqm4L96D6DzHh1-Gej19TQ9zPIFhAgG_c',
    appId: '1:875845800587:web:2acc2d42ef391a4456ba8e',
    messagingSenderId: '875845800587',
    projectId: 'inzdemo-6c004',
    authDomain: 'inzdemo-6c004.firebaseapp.com',
    storageBucket: 'inzdemo-6c004.firebasestorage.app',
    measurementId: 'G-52TLQF805S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNc31Pm1MSIiWe24_m-gzTBHyjGfWsDVE',
    appId: '1:875845800587:android:5eb8960b3835759556ba8e',
    messagingSenderId: '875845800587',
    projectId: 'inzdemo-6c004',
    storageBucket: 'inzdemo-6c004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd90gkX6mt_-d1B62lASuJhK4LSyeruw4',
    appId: '1:875845800587:ios:7cc6ebf593c25b7d56ba8e',
    messagingSenderId: '875845800587',
    projectId: 'inzdemo-6c004',
    storageBucket: 'inzdemo-6c004.firebasestorage.app',
    iosBundleId: 'com.example.worktick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd90gkX6mt_-d1B62lASuJhK4LSyeruw4',
    appId: '1:875845800587:ios:7cc6ebf593c25b7d56ba8e',
    messagingSenderId: '875845800587',
    projectId: 'inzdemo-6c004',
    storageBucket: 'inzdemo-6c004.firebasestorage.app',
    iosBundleId: 'com.example.worktick',
  );
}
